package com.rule.model;

import java.io.Serializable;
import java.time.Instant;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonInclude;

import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * The Class CouponEntity.
 */
@Data
@EqualsAndHashCode(callSuper = false)
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
public class CouponEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	/** The id. */
	@ApiModelProperty(notes = "ID")
	@Id
	private String id;

	/** The batchId. */
	@ApiModelProperty(notes = "BatchID")
	@Field("batch_id")
	private String batchId;

	/** The code. */
	@ApiModelProperty(notes = "Code")
	@Field("code")
	private String code;

	/** The from date. */
	@ApiModelProperty(notes = "From Date")
	@Field("from_date")
	private Instant fromDate;

	/** The thru date. */
	@ApiModelProperty(notes = "Thru Date")
	@Field("thru_date")
	private Instant thruDate;

	/** The auto generated. */
	@ApiModelProperty(notes = "Auto Generated")
	@Field("auto_generated")
	private Boolean autoGenerated;

	/** The promotion id. */
	@ApiModelProperty(notes = "Promotion Id")
	@Field("promotion_id")
	private String promotionId;

	/** The codeGenerationStatus. */
	@ApiModelProperty(notes = "codeGenerationStatus")
	@Field("codeGenerationStatus")
	private String codeGenerationStatus;

	/** The created by. */
	@Field(name = "created_by")
	protected String createdBy;

	/** The created at. */
	@Field(name = "created_at")
	protected Instant createdAt;

	/** The modified by. */
	@Field(name = "updated_by")
	protected String updatedBy;

	/** The modified at. */
	@Field(name = "updated_at")
	protected Instant updatedAt;

	/** The domain id. */
	@Field(name = "domain_id")
	protected String domainId;

	/** The version. */
	@Version
	public Integer version;

}